export const DECREMENT_MACHINES_AVAILABLE = "DECREMENT_MACHINES_AVAILABLE";
export const ADD_MACHINES_STATION = "ADD_MACHINES_STATION";
export const CHANGE_ROUND = "CHANGE_ROUND";
export const RESET = "RESET";

export const FETCH_DATA_BEGIN = "FETCH_DATA_BEGIN";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";
