export const UPDATE_SCORE = "UPDATE_SCORE";
export const SET_TOTAL_SCORE = "SET_TOTAL_SCORE";
export const ADD_LAST_GAME = "ADD_LAST_GAME";

export const HANDLE_SUCCES_RATE = "HANDLE_SUCCES_RATE";
export const GET_SUCCES_RATE = "GET_SUCCES_RATE";

export const RESET_SCORES = "RESET_SCORES";
